### ISSUE TITLE
Float value done ratio 

### ISSUE THREAD

**Issue by ashrafalzyoud** [Angelinsky7/redmine_parent_percent#1]
Hi thx for your lovely plugin
If I can asking u?!

1_ I'm changing the type of column done_ratio to float
2_ setting the done ratio calculation from issue Field
3_ setting to calculate done ratio from subtask

4_ I using formula
@issue.done_ratio = @ issue.custom.field.value(1).to_f.round(2)

5_ every things in child issue okay with float numbers done ratio 

6_ the problem in parent task
The done ratio appear 61%
I need look to 60.69%
   
      Example 
      child1 (:done_ratio => 10.12)
      child2 (:done_ratio => 20.23)
      child3(:done_ratio => 90.45)
      (10.12 + 20.33 + 90.44) / 3 = 12
       parent.issue.done_ratio=60.49
If u can help where  in core redmine code how calculate done ratio round

Or by using your plugin?!

**Comment by Angelinsky7** [comment]
@ashrafalzyoud i'm not sure to totally understand what you mean.... but if you look at this line  https://github.com/Angelinsky7/redmine_parent_percent/blob/c0c2e68f88ebfd1c0cc3c8cb83ae0d5e21099049/lib/redmine_parent_percent/issue_patch.rb#L30 i'm rounding the result of the progress.

i think you should change this to use floating value instead...

Maybe you're best course of action could be to fork this plugin and change the rounding bit to better suit your need ? (or create a MR to add an option to change the rouding calculation method between round to float...)

Was this helping ? (not sure....)

**Comment by ashrafalzyoud** [comment]
This plugin working in Redmine 5.1??

In core redmine where I can find how calculate done ratio in parent?!

**Comment by Angelinsky7** [comment]
@ashrafalzyoud sorry, i didn't maintain this plugin, so i've got absolutely no idea if this is working in redmine 5.1.
the last time i did something with redmine was 4 years ago... so it's pretty sure that something have changed.
i don't have the time to look into it... so good luck. :-)

**Comment by ashrafalzyoud** [comment]
I found in
App/models/assue.rb
Line 1853

if p.done_ratio_derived? # done ratio = average ratio of children weighted with their total estimated hours unless Issue.use_status_for_done_ratio? && p.status && p.status.default_done_ratio children = p.children.to_a if children.any? child_with_total_estimated_hours = children.select {|c| c.total_estimated_hours.to_f > 0.0} if child_with_total_estimated_hours.any? average = Rational( child_with_total_estimated_hours.sum(&:total_estimated_hours).to_s, child_with_total_estimated_hours.count ) else average = Rational(1) end done = children.sum do |c| estimated = Rational(c.total_estimated_hours.to_f.to_s) estimated = average unless estimated > 0.0 ratio = c.closed? ? 100 : (c.done_ratio || 0) estimated * ratio end progress = Rational(done, average * children.count) p.done_ratio = progress.floor 
end end end

But where change to round 2

**Comment by Angelinsky7** [comment]
again to sure to understand, but the line 1873 is the `floor` that you would like to change, no ?

**Comment by ashrafalzyoud** [comment]
Yes 
Progress.floor
Must change it
Progress.round(2)
??

**Comment by Angelinsky7** [comment]
or just `p.done_ratio = progress`

again this part of the code seems to have changed from the last time i look into it. You should try to fork the redmine project, change your line of code and make some test (i used a lot the debug console message for that) and if it's working like you want, create a plugin to change this method only.

Sadly you'll need to overwrite the complete `def recalculate_attributes_for(issue_id)` method for this to work... and maintains it every time the redmine team change it...

Apart from this i cannot help you more. Sorry
